### ISSUE TITLE
Busca em Vetor

### ISSUE THREAD

**Issue by eltonfonseca** [amandaadriene/c_studies#49]
Faça um programa em C que armazene 15 números inteiros em um vetor e depois permita que o usuário digite um número inteiro para ser buscado no vetor, se for encontrado o programa deve imprimir a posição desse número no vetor, caso contrário, deve imprimir a mensagem: "Nao encontrado!".

**Comment by amandaadriene** [comment]
pode ser valor fixo no vetor, 

achei o numero está na posição...
