### ISSUE TITLE
Descobrir a idade de uma pessoa

### ISSUE THREAD

**Issue by eltonfonseca** [amandaadriene/c_studies#9]
Escreva um programa que calcula a idade da pessoa, baseado na sua data de nascimento.
> Desafio: Tente fazer com que o próprio programa pegue a data atual automaticamente.

**Entrada**
```
Qual seu ano de nascimento? 1994
```

**Saída**
```
Sua idade é: 27 anos
```

**Comment by amandaadriene** [comment]
Faltou o desafio
